### PR TITLE
add the search bar

### PR DESCRIPTION
**Pull request by roua-moger**
add the search bar.
I don't know if I need all these files from Font awesome??

### CODE REVIEW

**Comment by MrTim** [comment]
@rouaaDPS  I'm actually scared to open the pull request for review :) Because I can see that there are 1678!!!! files changed. What are those files?)

**Comment by roua-moger** [comment]
They are from font awesom 😅😅

**Comment by MrTim** [comment]
You don't need all of them for sure! If you're using icon -> then it's ok, but please delete the rest of icons from the repo)

**Comment by roua-moger** [comment]
I delete them .. thanks Ivan :)

**Comment by keponk** [comment]
hi @rouaaDPS this pull request is showing conflicts with the style css file. Normally this happens when we edit the file accidentally in a different branch, basically git sees some changes it doesn't recognize.

Another thing, regarding font awesome you have a couple choices. The most common way i see it used is to import it as a library the same way you imported the Bootstrap css. FontAwesome wants you to give them your email to provide a link BUT it's so popular that it is super easy to find alternative links like this one: https://www.bootstrapcdn.com/fontawesome/
Another option, to save a little bit of bandwitdth is to manually download literally just the svg files you need (assuming they are only handful) and manually use them with a `` tag or similar.  

With both of this options you don't need to maintain a fontawesome folder at all, similar to how you dont need to keep a bootstrap folder either. I personally prefer the 1st option, it is only 30kb :angel:

**Comment by roua-moger** [comment]
@keponk thank you so much, I searched for a link in the font awesome website but can't find. 
About the conflicts in my style file, I think that is normal because I worked in 2 branches at the same time.  Can I solve them before the merge? or only after the merge and pull?

**Comment by keponk** [comment]
@rouaaDPS the right way is to fix all conflict before the pull request can be accepted :) 

I recommend to check the version in master and your version to see what is happening. if you are feeling brave you can look into `git rebase` but I remember this took me a long time to understand :P

**Comment by roua-moger** [comment]
@keponk I fixed the conflict :)

**Comment by keponk** [comment]
Great job! and also, nice to see that gpg signature ;) a true symbol of a good developer :+1:

**Pull request merged**
